Models/Category.cs
using System.Collections.Generic;

public class Category
{
    public int CategoryId { get; set; }
    public string CategoryName { get; set; }
    public string Description { get; set; }
    public ICollection<Product> Products { get; set; }
 }

Models/CategoryViewModel.cs
public class CategoryViewModel
{
  public Product product { get; set; }
  public IEnumerable<Category> Categories { get; set; }
}

Models/Customer.cs
using System.ComponentModel.DataAnnotations;

    public class Customer
    {
        public int CustomerID { get; set; }
        [Required(ErrorMessage = "Company Name is required")]
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
    }

Models/Discount.cs
using System;
    public class Discount
    {
        public int DiscountID { get; set; }
        public int Code { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public int ProductID { get; set; }
        public decimal DiscountPercent { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

        public Product Product { get; set; }
    }

Models/EFNorthwindRepository.cs
using System.Linq;

    public class EFNorthwindRepository : INorthwindRepository
    {
        // the repository class depends on the NorthwindContext service
        // which was registered at application startup
        private NorthwindContext context;
        public EFNorthwindRepository(NorthwindContext ctx)
        {
            context = ctx;
        }
        // create IQueryable for Categories & Products
        public IQueryable<Category> Categories => context.Categories;
        public IQueryable<Product> Products => context.Products;
        public IQueryable<Discount> Discounts => context.Discounts;
        public IQueryable<Customer> Customers => context.Customers;

        public void AddCustomer(Customer customer)
        {
            context.Customers.Add(customer);
            context.SaveChanges();
        }
    }

Models/INorthwindRepository.cs
using System.Linq;

    public interface INorthwindRepository
    {
        IQueryable<Category> Categories { get; }
        IQueryable<Product> Products { get; }
        IQueryable<Discount> Discounts { get; }
        IQueryable<Customer> Customers { get; }

        void AddCustomer(Customer customer);
    }

Models/NorthwindContext.cs
using Microsoft.EntityFrameworkCore;

public class NorthwindContext : DbContext
{
  public NorthwindContext(DbContextOptions<NorthwindContext> options) : base(options) { }

  public DbSet<Category> Categories { get; set; }
  public DbSet<Product> Products { get; set; }
  public DbSet<Discount> Discounts { get; set; }
  public DbSet<Customer> Customers { get; set; }
  public void AddCustomer(Customer customer)
  {
    this.Add(customer);
    this.SaveChanges();
  }
}

Models/Product.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

public class Product
{
    public int ProductId { get; set; }
    public string ProductName { get; set; }
    public string QuantityPerUnit { get; set; }
    [Column(TypeName = "decimal(18,4)")]
    public decimal UnitPrice { get; set; }
    public short UnitsInStock { get; set; }
    public short UnitsOnOrder { get; set; }
    public short ReorderLevel { get; set; }
    public bool Discontinued { get; set; }
    public int CategoryId { get; set; }
    public Category Category { get; set; }
}

Controllers/CustomerController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
    public class CustomerController : Controller
    {
        // this controller depends on the BloggingRepository
        private NorthwindContext _dataContext;
        public CustomerController(NorthwindContext db) => _dataContext = db;

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(Customer customer)
        {
            if (ModelState.IsValid)
            {
                if (_dataContext.Customers.Any(c => c.CompanyName == customer.CompanyName))
                {
                    ModelState.AddModelError("", "Company Name must be unique");
                }
                else
                {
                    _dataContext.AddCustomer(customer);
                    return RedirectToAction("Index", "Home");
                }
            }
            return View();
        }
    }

Controllers/HomeController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;

    public class HomeController : Controller
    {
        // this controller depends on the NorthwindRepository
        private NorthwindContext _dataContext;
        public HomeController(NorthwindContext db) => _dataContext = db;

        public ActionResult Index() => View(_dataContext.Discounts
            .Where(d => d.StartTime <= DateTime.Now && d.EndTime > DateTime.Now)
            .Take(3));
    }

Controllers/ProductController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;

    public class ProductController : Controller
    {
        // this controller depends on the NorthwindRepository
        private NorthwindContext _dataContext;
        public ProductController(NorthwindContext db) => _dataContext = db;

        public IActionResult Category() => View(_dataContext.Categories.OrderBy(c => c.CategoryName));
        public IActionResult Index(int id) => View(_dataContext.Products.Where(p => p.CategoryId == id && p.Discontinued == false).OrderBy(p => p.ProductName));
        public IActionResult Discounts() => View(_dataContext.Discounts.Where(d => d.StartTime <= DateTime.Now && d.EndTime > DateTime.Now));
    }

Views/Customer/Register.cshtml
@model Customer
<h2 class="mt-3"><i class="far fa-address-card"></i> Customer Register</h2>

<form method="post" asp-action="Register">
    <div asp-validation-summary="All" style="color:red;"></div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="@Model.CompanyName">Company Name</label>
            <input asp-for="@Model.CompanyName" class="form-control" placeholder="Company Name" />
        </div>
        <div class="form-group col-md-6">
            <label asp-for="@Model.Address">Address</label>
            <input asp-for="@Model.Address" class="form-control" placeholder="Address" />
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-3">
            <label asp-for="@Model.City">City</label>
            <input asp-for="@Model.City" class="form-control" placeholder="City" />
        </div>
        <div class="form-group col-md-3">
            <label asp-for="@Model.Region">Region</label>
            <input asp-for="@Model.Region" class="form-control" placeholder="Region" />
        </div>
        <div class="form-group col-md-3">
            <label asp-for="@Model.PostalCode">Postal Code</label>
            <input asp-for="@Model.PostalCode" class="form-control" placeholder="Postal Code" />
        </div>
        <div class="form-group col-md-3">
            <label asp-for="@Model.Country">Country</label>
            <input asp-for="@Model.Country" class="form-control" placeholder="Country" />
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="@Model.Phone">Phone</label>
            <input asp-for="@Model.Phone" class="form-control" placeholder="Phone" />
        </div>
        <div class="form-group col-md-6">
            <label asp-for="@Model.Fax">Fax</label>
            <input asp-for="@Model.Fax" class="form-control" placeholder="Fax" />
        </div>
    </div>
    
    <button type="submit" class="btn btn-outline-primary">Register</button>
</form>

Views/Home/Index.cshtml
@model IEnumerable<Discount>

<div class="jumbotron my-2 border border-secondary">
    <h1 class="display-4">Northwind</h1>
    <p class="lead">We have the best prices and selection of high quality foods &amp; beverages on the planet! Check out our featured discounts below.</p>
    <hr class="my-4">
    <p>For exceptional international quisuine, look no further.</p>
    <a class="btn btn-outline-primary btn-lg" href="#" role="button"><i class="fas fa-shopping-cart"></i> Order Now</a>
</div>

<div class="row">
    @foreach (Discount d in Model)
    {
        <div class="col-md m-3 p-3 discounts">
            <h3>@d.Title</h3>
            <div class="mb-4">
                @d.Description
            </div>
            <i>Discount expires: @d.EndTime.ToString("MM/dd/yyyy")</i><br />
            <a href="#" class="code" data-code="@d.Code" data-product="@d.Title"><i class="far fa-hand-point-right"></i> Discount Code</a>
        </div>
    }
</div>

@section scripts
    {
    <script src="/js/client.js"></script>
}

Views/Product/Category.cshtml
@model IEnumerable<Category>

<div class="bg-primary m-1 p-1 text-white"><h4>Categories</h4></div>
<ul class="list group">
  @foreach (Category category in Model)
  {
    <li class="list-group-item">
      <a asp-action="Index" asp-route-id="@category.CategoryId">@category.CategoryName</a> - @category.Description</li>
  }
</ul>

Views/Product/Discounts.cshtml
@model IEnumerable<Discount>


<h2 class="mt-3"><i class="fas fa-tag"></i> Product Discounts</h2>
<div class="list-group">
    @foreach (Discount d in Model)
    {
        <div class="list-group-item">
            @d.Title<br />
            @d.Description<br />
            Discount Expires: <i>@d.EndTime.ToString("MM/dd/yyyy")</i><br />
            <a href="#" class="code" data-code="@d.Code" data-product="@d.Title"><i class="far fa-hand-point-right"></i> Discount Code</a>
        </div>
    }
</div>

@section scripts
    {
    <script src="/js/client.js"></script>
}

Views/Product/Index.cshtml
@model IEnumerable<Product>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Product</th>
            <th scope="col" class="text-right">Price</th>
            <th scope="col" class="text-right">Stock</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Product p in Model)
        {
        <tr>
            <td>@p.ProductName</td>
            <td class="text-right">@string.Format("{0:c}", p.UnitPrice)</td>
            <td class="text-right">@p.UnitsInStock</td>
        </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <!-- font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <!-- client -->
    <link rel="stylesheet" href="~/css/client.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="far fa-compass"></i> Northwind</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-database"></i> Products
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-action="Category" asp-controller="Product"><i class="fas fa-list-ul"></i> Browse Categories</a>
                                <a class="dropdown-item" href="#"><i class="fas fa-search"></i> Product Search</a>
                                <div class="dropdown-divider"></div>
                                 <a class="dropdown-item" asp-action="Discounts" asp-controller="Product"><i class="fas fa-tag"></i> Current Discounts</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="customerDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-users"></i> Customers
                    </a>
                    <div class="dropdown-menu" aria-labelledby="customerDropdown">
                        <a class="dropdown-item" href="#"><i class="fas fa-user"></i> Account</a>
                        <a class="dropdown-item" asp-controller="Customer" asp-action="Register"><i class="far fa-address-card"></i> Register</a>
                        <a class="dropdown-item" href="#"><i class="fas fa-sign-in-alt"></i> Sign In</a>
                    </div>
                        </li>
                    </ul>
                </div>
                <form class="form-inline my-2 my-lg-0 d-none d-md-inline">
                    <input class="form-control mr-sm-2" type="search" placeholder="Product Search" aria-label="Search">
                    <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i><span class="sr-only">Search</span></button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        @RenderBody()
    </div>
    <!-- toast -->
    <div id="toast" class="toast">
        <div class="toast-header">
            <strong class="mr-auto" id="product">Product Name</strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
            Discount Code: <strong id="code">CODE</strong>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Northwind
        </div>
    </footer>
    <!-- jquery -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <!-- bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>